version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "j4boot-coffee-service"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-5pmxde9sh468"
s3_prefix = "j4boot-coffee-service"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

