AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot API - com.j4boot.aws.lambda.coffee::j4boot-coffee-service-v1
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  J4bootCoffeeServiceV1Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.j4boot.aws.lambda.coffee.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: ./target/j4boot-coffee-service-v1-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        ProxyResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  J4bootCoffeeServiceV1Api:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: J4bootCoffeeServiceV1Api
